---
framework: mocha
blacklist:
  - "test/log-exception.test.js##Logger, ExceptionHandler##.exceptions.unhandle()##handlers immutable"
  - "test/log-exception.test.js##Logger, ExceptionHandler##Custom exitOnError function does not exit"
postmerge:
  pattern:
    - "./test/log-exception.test.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
modifiers:
  - type: mocha
    config: cnf/mocha.ini
  - type: jest
    cli: "--forbid-pending --no-bail"
premerge:
  - "./test/log-exception.test.js"
prerun:
  - npm ci
postrun:
  - node --version
  - echo "Ba Dum TAS... -_-"
stability:
  consecutive_runs: 5
version: 2.0
