---
blacklist:
  - 'test/log-exception.test.js##Logger, ExceptionHandler##Custom exitOnError function does not exit##'
framework: mocha
postMerge:
  pattern:
    - "./test/**/*.test.js"
preMerge:
  pattern:
    - "./test/**/*.test.js"
preRun:
  - npm ci
postRun:
  - node --version
  - echo "Ba Dum TAS... -_-"
stability:
  consecutive_runs: 5
configFile: .mocharc.json
version: 2.2

