---
framework: mocha
postMerge:
  pattern:
    - "./test/**/*.test.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./test/**/*.test.js"
preRun:
  - npm ci
  - populist lib/*.js lib/winston/*.js lib/winston/**/*.js
postRun:
  - node --version
  - echo "Ba Dum TAS... -_-"
stability:
  consecutive_runs: 5
version: 2.0
