---
framework: mocha
blacklist:
  - test/rejection-handler.test.js##UnhandledRejectionHandler##.handle()
postmerge:
  pattern:
    - "./test/**/*.test.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
premerge:
  - "./test/**/*.test.js"
prerun:
  - npm ci
postrun:
  - node --version
  - echo "Ba Dum TAS... -_-"
stability:
  consecutive_runs: 5
configFile: ".tas.mocharc.json"
version: 2.0
